services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hergo_back_app
    env_file:
      - ./hergo-back/.env
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://zeynab:nouveaumotdepasse@postgres:5432/hebergo?schema=public
      CLOUDINARY_FOLDER: hergo
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./hergo-back:/app
      - /app/node_modules
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: hergo_postgres
    ports:
      - "55432:5432"
    environment:
      POSTGRES_DB: hebergo
      POSTGRES_USER: zeynab
      POSTGRES_PASSWORD: nouveaumotdepasse
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zeynab -d hebergo"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pg_data:
