[front]
front_host ansible_host=51.21.253.138 ansible_user=ubuntu

[back]
back_host ansible_host=172.31.23.29 ansible_user=ubuntu

[db]
db_host ansible_host=172.31.21.152 ansible_user=ubuntu

[all:vars]
ansible_python_interpreter=/usr/bin/python3

[back:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q -i ~/.ssh/TERRAFORM.pem -o StrictHostKeyChecking=no ubuntu@51.21.253.138"'

[db:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q -i ~/.ssh/TERRAFORM.pem -o StrictHostKeyChecking=no ubuntu@51.21.253.138"'
