[front]
front_host ansible_host=16.171.70.167 ansible_user=ubuntu

[back]
back_host ansible_host=172.31.14.111 ansible_user=ubuntu

[db]
db_host ansible_host=172.31.8.149 ansible_user=ubuntu

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/TERRAFORM.pem

[back:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q -i ~/.ssh/TERRAFORM.pem -o StrictHostKeyChecking=no ubuntu@16.171.70.167" -o StrictHostKeyChecking=no'

[db:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q -i ~/.ssh/TERRAFORM.pem -o StrictHostKeyChecking=no ubuntu@16.171.70.167" -o StrictHostKeyChecking=no'
